services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 5
    volumes:
      - ./Predictfluence/postgres_data:/var/lib/postgresql
            
  pgadmin:  
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - ./Predictfluence/pgadmin_data:/var/lib/pgadmin
    depends_on: 
      - db

  api:
    build:
      context: ./Predictfluence/api
      dockerfile: Dockerfile
    volumes:
      - ./Predictfluence/api:/api
      - ./Predictfluence/etl/Database:/api/Database:ro
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - etl

  app:
    container_name: streamlit_app
    build:
      context: ./Predictfluence/app
      dockerfile: Dockerfile
    volumes:
      - ./Predictfluence/app:/app
    ports:
      - 8501:8501
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

  etl:
    container_name: etl_service
    build:
      context: ./Predictfluence/etl
      dockerfile: Dockerfile
    volumes:
      - ./Predictfluence/etl:/etl
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CSV_FOLDER=/etl/data
    depends_on:
      db:
        condition: service_healthy
    command: python etl.py
    restart: "no"

  ds:
    container_name: ds_service
    build:
      context: ./Predictfluence/ds
      dockerfile: Dockerfile
    volumes:
      - ./Predictfluence/ds:/ds
      - ./Predictfluence/etl/Database:/ds/Database:ro
    ports:
      - 8010:8010
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - etl
